name: Run e2e Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: mypet

      redis:
        image: redis
        ports:
          - 6379:6379

    env:
      JWT_SECRET: testing
      DATABASE_URL: postgresql://docker:docker@postgres:5432/mypet?schema=public

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"

      - run: npm ci

      - run: npm run test:e2e
